In [18]:
%reload_ext autoreload
%autoreload 2
from utils import cellvit_seg
import pandas as pd
import ast

In [28]:
vote_df = pd.read_csv('/t9k/mnt/zsk/workspace/HEST/project/mulitimodel_fusion/single_cell_annotation/annotation_output/Breast/vote_output/10X_80%.csv',index_col = 0)
seg_path = '/t9k/mnt/zsk/workspace/HEST/dataset/hest_data/cellvit_seg'
adata_path = '/t9k/mnt/zsk/workspace/HEST/dataset/hest_data/st'

In [17]:
vote_df.iloc[0]['vote_type']

"['Malignant']"

In [29]:
vote_df['vote_type'] = vote_df['vote_type'].apply(lambda x: ast.literal_eval(x)[0] if isinstance(ast.literal_eval(x), list) else x)

In [30]:
vote_df.to_csv('/t9k/mnt/zsk/workspace/HEST/project/mulitimodel_fusion/single_cell_annotation/annotation_output/Breast/vote_output/10X_80%.csv',index=True)

In [31]:
vote_df[(vote_df['vote_type']=='Malignant') | (vote_df['vote_type']=='Epithelial')]

                           c2l_annotation rctd_annotation   sample  vote_type
NCBI776_AACATCTAATGACCGG-1  ['Malignant']   ['Malignant']  NCBI776  Malignant
NCBI776_AACATCTTAAGGCTCA-1  ['Malignant']   ['Malignant']  NCBI776  Malignant
NCBI776_AACCTACTGTAACTCA-1  ['Malignant']   ['Malignant']  NCBI776  Malignant
NCBI776_AACCTGACAGTGCCGC-1  ['Malignant']   ['Malignant']  NCBI776  Malignant
NCBI776_AACCTTAGCGTCCGGT-1  ['Malignant']   ['Malignant']  NCBI776  Malignant
...                                   ...             ...      ...        ...
TENX68_TGTTCAGAACGGTGTA-1   ['Malignant']   ['Malignant']   TENX68  Malignant
TENX68_TGTTCTGCTCTGTCGT-1   ['Malignant']   ['Malignant']   TENX68  Malignant
TENX68_TGTTGCGTCCAAGATT-1   ['Malignant']   ['Malignant']   TENX68  Malignant
TENX68_TGTTGGATGGACTTCT-1   ['Malignant']   ['Malignant']   TENX68  Malignant
TENX68_TGTTGGCCAGACCTAC-1   ['Malignant']   ['Malignant']   TENX68  Malignant

[6965 rows x 4 columns]

In [27]:
vote_df.iloc[0].index

Index(['Unnamed: 0', 'c2l_annotation', 'rctd_annotation', 'sample',
       'vote_type'],
      dtype='object')

In [26]:
type(vote_df.iloc[0].index)

pandas.core.indexes.base.Index

In [47]:
refine_df = cellvit_seg.fining_epi_can_annotation(vote_df,seg_path,adata_path,condition=0.7)

In [48]:
refine_df[refine_df['HE_type']==1]

,c2l_annotation,rctd_annotation,sample,vote_type,HE_type
TENX13_AAACCGGGTAGGTACC-1,['Malignant'],['Malignant'],TENX13,Malignant,1.0
TENX13_AAACGGGCGTACGGGT-1,['Malignant'],['Malignant'],TENX13,Malignant,1.0
TENX13_AAATAGCTTAGACTTT-1,['Malignant'],['Malignant'],TENX13,Malignant,1.0
TENX13_AAATCTAGCCCTGCTA-1,['Malignant'],['Malignant'],TENX13,Malignant,1.0
TENX13_AAATGGTCAATGTGCC-1,['Malignant'],['Malignant'],TENX13,Malignant,1.0
...,...,...,...,...,...
TENX39_TGTTGTCAAGAAGTCT-1,['Malignant'],['Malignant'],TENX39,Malignant,1.0
TENX39_TTACATGCCACAACTA-1,['Malignant'],['Malignant'],TENX39,Malignant,1.0
TENX39_TTACCCTAACAGTCCT-1,['Malignant'],['Malignant'],TENX39,Malignant,1.0
TENX39_TTGACGCTCCATGAGC-1,['Malignant'],['Malignant'],TENX39,Malignant,1.0
TENX39_TTGCTGATCATGTTCG-1,['Malignant'],['Malignant'],TENX39,Malignant,1.0

In [49]:
len(refine_df[refine_df['HE_type']==2])

41

In [46]:
refine_df.to_csv('./temporary_data/refined_breast_10X.csv',index=True)